---
name: Pull Request Target

on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    - edited
    - ready_for_review

jobs:
  label-needs-review:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Labels
        uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20 # v4.2.0
        if: github.event.action == 'opened'
        with:
          configuration-path: .github/labeler-pull-requests.yml
          repo-token: '${{ secrets.GITHUB_TOKEN }}'      
