---
name: Test

on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    paths-ignore:
      - README.md

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Install Dependencies
        run: go mod download
      - name: Build
        run: go build -v .
      - name: Run Generate
        run: go generate ./...
      - name: Check Generated Code
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
